#!/bin/bash
set -e

# ─────────────────────────────────────────────
#  SSH Setup & Hardening Script
#  For Ubuntu/Debian based servers
# ─────────────────────────────────────────────

SSH_PORT=22          # Change this to a custom port (e.g. 2222) for extra security
SSHD_CONF="/etc/ssh/sshd_config"
BACKUP_CONF="/etc/ssh/sshd_config.bak.$(date +%Y%m%d%H%M%S)"

echo "======================================"
echo " SSH Setup & Hardening"
echo "======================================"

# ── 1. Backup existing config ─────────────────
echo "[1/6] Backing up current SSH config..."
sudo cp $SSHD_CONF $BACKUP_CONF
echo "  → Backup saved to: $BACKUP_CONF"

# ── 2. Generate SSH key pair (on this server) ─
echo "[2/6] Checking SSH key..."
if [ ! -f ~/.ssh/id_ed25519 ]; then
    ssh-keygen -t ed25519 -C "$(whoami)@$(hostname)" -f ~/.ssh/id_ed25519 -N ""
    echo "  → Key generated: ~/.ssh/id_ed25519"
else
    echo "  → SSH key already exists, skipping."
fi

echo ""
echo "  ★ Your PUBLIC key (share this to servers you want to access):"
echo "  ──────────────────────────────────────────────────────────────"
cat ~/.ssh/id_ed25519.pub
echo "  ──────────────────────────────────────────────────────────────"
echo ""

# ── 3. Setup authorized_keys ──────────────────
echo "[3/6] Setting up authorized_keys..."
mkdir -p ~/.ssh
touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys

echo ""
echo "  → To allow a client to SSH into this server, paste their public key:"
echo "     echo 'ssh-ed25519 AAAA...' >> ~/.ssh/authorized_keys"
echo ""

# ── 4. Harden SSH config ──────────────────────
echo "[4/6] Applying SSH hardening..."
sudo bash -c "cat > $SSHD_CONF" <<EOF
# ─── SSH Server Configuration ───────────────
# Generated by setup_ssh.sh

Port $SSH_PORT
AddressFamily inet

# ─── Authentication ──────────────────────────
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PermitEmptyPasswords no
MaxAuthTries 4
LoginGraceTime 30

# ─── Security ────────────────────────────────
Protocol 2
X11Forwarding no
AllowTcpForwarding no
PermitUserEnvironment no
ClientAliveInterval 300
ClientAliveCountMax 2

# ─── Logging ─────────────────────────────────
LogLevel VERBOSE
SyslogFacility AUTH

# ─── SFTP ────────────────────────────────────
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

echo "  → SSH config written."

# ── 5. Allow SSH port in firewall ─────────────
echo "[5/6] Configuring firewall (ufw)..."
if command -v ufw &>/dev/null; then
    sudo ufw allow $SSH_PORT/tcp comment "SSH"
    sudo ufw --force enable
    echo "  → Port $SSH_PORT allowed in ufw."
else
    echo "  → ufw not found, skipping firewall setup."
    echo "     Make sure port $SSH_PORT is open manually."
fi

# ── 6. Restart SSH service ────────────────────
echo "[6/6] Restarting SSH service..."
sudo sshd -t  # Test config before restarting
sudo systemctl restart sshd
echo "  → SSH restarted successfully."

# ── Done ──────────────────────────────────────
echo ""
echo "======================================"
echo " SSH Setup Complete!"
echo "======================================"
echo " Port           : $SSH_PORT"
echo " Root login     : DISABLED"
echo " Password auth  : DISABLED (key only)"
echo " Config file    : $SSHD_CONF"
echo " Config backup  : $BACKUP_CONF"
echo ""
echo " HOW TO CONNECT FROM YOUR MACHINE:"
echo "   ssh -i ~/.ssh/id_ed25519 $(whoami)@$(hostname -I | awk '{print $1}') -p $SSH_PORT"
echo ""
echo " ⚠  WARNING: Password auth is now OFF."
echo "    Make sure your public key is in:"
echo "    ~/.ssh/authorized_keys"
echo "    BEFORE closing this session!"
echo "======================================"
